# Generated by Django 5.0.4 on 2024-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_gallery_video_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
