# Generated by Django 5.0.4 on 2024-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_gallery_title_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivitasationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('fullname', models.CharField(max_length=30)),
            ],
        ),
    ]
