# Generated by Django 5.0.4 on 2024-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_privitasationusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privitasationusers',
            name='fullname',
        ),
        migrations.AddField(
            model_name='privitasationusers',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privitasationusers',
            name='kra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privitasationusers',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='privitasationusers',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
